### ISSUE TITLE
Ride request screen have buttons out of screen

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#115]
Buttons are below visibility:
<img src="https://cloud.githubusercontent.com/assets/1442758/15452463/ea91c870-1ff7-11e6-8160-b5efba306f5c.jpg" width=200px />

**Comment by ArnoldasSid** [comment]
Should be fixed?

**Comment by spastai** [comment]
Please use https://help.github.com/articles/closing-issues-via-commit-messages/ to mark issues resolved.
Now it's not clear are you planning to solve or it is solved already
