### ISSUE TITLE
Wireframe for 0.1.15 version

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#177]
Rider doesn't care about drivers starting (A) and finish (B) points.
![match-request-confirm](https://cloud.githubusercontent.com/assets/1442758/16806152/02abc332-491c-11e6-8483-4028ab1a0c93.png)

He should see: 
His starting point (rA) - pickup stop (sA) - drop-off stop (sB)

**Comment by spastai** [comment]
<img src=https://cloud.githubusercontent.com/assets/1442758/16866194/e4f73382-4a72-11e6-9ebc-5425b6fb95d1.png width=250 /><img src=https://cloud.githubusercontent.com/assets/1442758/16866195/e73b9ff2-4a72-11e6-8327-b48b1bf0a657.png width=250 /><img src=https://cloud.githubusercontent.com/assets/1442758/16866198/eb58e9f0-4a72-11e6-8ac8-bf4ada5799d4.png width=250 /><img src=https://cloud.githubusercontent.com/assets/1442758/16866201/f11a2ed0-4a72-11e6-91b0-8a6f07ab36e3.png width=250 />

**Comment by spastai** [comment]
RideInfo should turn into 
TripInfo(A, sA, sB, B)
together with 
GoogleMap(ride, drive)
if(null == ride) show drive
if(null == drive) show ride
if(ride & drive) show A,B markers for ride and drive with stops

**Comment by spastai** [comment]
1. TripInfo component - we need to agree what to show on map and below it:
   3.1 YourRide:
   - Picture - Driver
     - Trip points - Your start point, stop where you join trip, stop where you leave trip, your finish point
     - Stuff at bottom - Leave Ride button? Information about other passengers?
       3.2 RideRequest:
   - Picture - Driver
     - Trip points - If your trip start and end points not known then it should show trip start point, end point and all stops else same as RideRequest
     - Stuff at bottom - Request Ride button. Something else?
       3.3 YourDrive:
   - Picture - Your own picture?
     - Trip points - Trip start point, end point and all stops where you have to pick up people (both confirmed and requests, maybe show different colors for confirmed and requests, maybe show numbers next to stops how many people you need to pick up?)
     - Stuff at bottom - List of all confirmed people? List of all requests with accept/reject buttons?
     - What happens when drive is not recurring?

**Comment by VaivaK** [comment]
Ride request keliones sudeliojimas turi buti kaip sitame wireframe - su passenger keliones taskais a ir ba ir kelione pestute iki kur ji paims ir nuo kur ji paleis.
![screen shot 2016-08-01 at 10 35 40](https://cloud.githubusercontent.com/assets/17546849/17286704/d8eb2026-57d3-11e6-80f2-75edec30888b.png)

**Comment by spastai** [comment]
![()[https://github.com/spastai/vilnius-carpool/raw/develop/docs/wireframe/0.1.15/match-request-confirm.png]](https://github.com/spastai/vilnius-carpool/raw/develop/docs/wireframe/0.1.15/match-request-confirm.png)
click to zoom the picture.

Please review wireframe after our Mondays discussion.
Pictures are used from old one.
Comment each view:
1. View 1: ok
2. View 2:  button should be... map should show

From View 5 should go to View 6 when user  press button

**Comment by VaivaK** [comment]
View 1: nu man šiandien jau akys išvarvėjo, bet nematau aš to view 1 :-)
View 2: driver passenger irgi removed. paspaudus "drive" kelione issisaugo ir ant ekrano push info kad jusu kelione sekmingai issaugota. tada ekrane "your ride" view 4
View 3: button "save ride" ir  "save ride request". Paspaudus "save ride" ziureti view2 komentarus. Paspaudus "save ride request" uzklausa issisaugo ir ant ekrano push info kad jusu keliones uzklausa sekmingai issaugota.  tada ekrane panasus kaip view 7. Pavadinkime ji view 7_2 tik foto ne driver, o rider tuo metu. arba jokios, nes dar nera jokio vairuotojo. nera stoteliu, button "cancel", itinery - A and B points, arrive time, no stops. 
View 4: ok
View 5: list yra padalintas i 2 stulpelius kaip pridetoj foto, tik pavadinimai "your rides" ir your requests"
![screen shot 2016-08-04 at 17 34 46](https://cloud.githubusercontent.com/assets/17546849/17405914/0ca48d06-5a6a-11e6-86e8-1b8bf9712226.png)

View 6: ok
View 7: ok
View 8: ne "review", o "view"
View 9: ne "review", o "view". "shows list of requests" SIta dalis matosi view 9.
View 10: nera "shows list of requests" SIta dalis matosi view 9. Confirm and cancel (ne withdraw).
View 11: ok, nes nelabai matosi kaip cia kas atrodys :D

**Comment by spastai** [comment]
![match-request-confirm](https://cloud.githubusercontent.com/assets/1442758/17427371/d52e3082-5ae8-11e6-9556-83b128eea99a.png)

View1: Tu teisi, tokio view nėra
View2: Papildžiau, ką reikia pašalinti, tik paspaudus [Drive] manau ne View4 (nes tai yra riderio langas, o View6
View3: Turbut "save ride" turima omenyje "Save Drive"? Tada "save ride request" taps "Save Ride". Pagal musu susitarimus driverio kelione - drive, riderio - ride. Kodel netinka rodykles kaip dabar, t.y.  einama į View4? Nes view4 yra "panasus kaip view 7"
View9: View10 esantis "shows list of requests" - tai kai matydamas savo kelione tu matai visa prasytoju sarasa. View9 yra notifications sarasas
View10: Del mygtuku - pataisiau.

**Comment by VaivaK** [comment]
View2 ne, "save drive". Praėjusi karta kalbėdami skype sutarėme, kad view2 yra pradinis langas visoms paieškoms, bet jame išsaugoti kelione tiesiai gali tik driveris. Rideris spaudžia spaudžia search ir tik neradęs jam tinkančios keliones gali išsaugoti requesta. Bet kadangi tame lange jam nemeta užregistruotų kelionių listo jis čia nieko negali saugoti kol ne pasitikrino kad yra jam tinkamu.
View3 atsakymas ties view2. Jei neaiškiai parašau - susiskambinkime kuo skubiau 15min skype ir pabandysiu papasakoti, gal bus paprasčiau.
View 9 yra notification sąrašas riderio, T.y. Visas sąrašas tavo noificationu / užklausų. Todėl to nebereikia view10. Driver notifications matosi view 8.

**Comment by ArnoldasSid** [comment]
Apie view10 (gal verta net atskirą issue sukurt?)

Tai idėja dėl pačių notifications, kad tu jį pmatęs gali iš karto paconfirminti (nes pvz. tikėjais requesto arba šiaip esi geras žmogus ir visus labai mėgsti) arba gali įsijungti kažkokią detalesnę informaciją ir tada pažiūrėjęs kad viskas patinka patvirtini kelionę. Iki šiol wireframuose turėjom:
- YourDrive (į kurį nueini MyTrips -> Drives -> Ant tripo paspaudi)
- DriveConfirm (kuris irgi rodo tavo drive, bet į jį nueini gavęs notification ir paspaudęs View/Review)

Mano idėja, kad DriveConfirm atskiro screeno mum turėti nereikia ir padaryti universalesnį YourDrive.
Kas manau kad turėtų įeiti į YourDrive:
- Žemėlapis
- Adresai pradžios ir pabaigos taškų
- Nuotrauka nereikalinga?
- Sąrašas patvirtintų pakeleivių
- Sąrašas žmonių kurie requestino šito drive
- Sąrašas žmonių su kuriais sumatchina drive ir kuriem gali jį pasiūlyti?

Žemėlapy ir sąraše sustojimus rodytume tik tuos kur yra confirmed/requestų ir tada galėtume skirtingom spalvom pažymėti ant žemėlapio kur žmonės requestina kad tu sustotum, kur tu jau patvirtinęs kad sustosi.

Apibendrinus idėja yra turėti labai informatyvų YourDrive screen'ą kuriame yra visa įmanomą informacija apie konkretų sukurtą drive. Problema kad reik tai sutalpinti į pakankamai mažą mobilų ekraną. Pasidalinkit savo mintim apie visą tai :)

**Comment by spastai** [comment]
Check #172 for agreements on View10.
All other Views are reviewed and confirmed
