### ISSUE TITLE
Drive.time should be set to trip start date, not trip finish date

### ISSUE THREAD

**Issue by ArnoldasSid** [vilnius/vilnius-carpool#188]

**Comment by spastai** [comment]
Please provide description.
There is no class Drive. 
There is Trip (general one) and saving it is calculated from bTime - tripDuration:
https://github.com/vilnius/vilnius-carpool/blob/develop/src/packages/carpool-service/client/CarpoolServiceClient.coffee#L124

**Comment by ArnoldasSid** [comment]
Time of ride is not shown anymore in RidesList, therefore I'm closing this
