### ISSUE TITLE
Repeating Days

### ISSUE THREAD

**Issue by ArnoldasSid** [vilnius/vilnius-carpool#200]
Kažką kalbėjom, bet nieko konkretaus lyg ir nenusprendėm, tai manau verta susikurti issue kur bent jau susirašyti argumentus už ir prieš Repeating Days ir kaip visą tai įgyvendinti.

Pagrindinė idėja - Jei aš esu driveris ir kasdien važinėju į darbą kasdien kurti trip'ą (ypač pradžioj kai turbūt dažniausiai niekas ir neprisijungs) tikrai mane užknis, todėl reiktų šitą variantą padaryti patogiai. Kad driveris vieną kartą susikutų tripą kuriuo jis važinėja pastoviai (pvz. į darbą) ir gali jį pamiršti, jei kažką tas trip'as sudomins, tai jis gaus notificationą. Manau feature labai svarbus įvertinant mūsų tikslinę auditoriją.

Pagr. klausimai/problemos:
- Ar šita alternatyva reikalinga rideriui?
- Kaip tada šiuo atrodo YourDrive (apie jį daugiau rašiau #177)?
- Alternatyva - kaip jum variantas jei pvz driveris ne susikuria repeating kelionę, o tiesiog būtų kokia funkcija kad jis gali vienu kartu susikurti daug identiškų kelionių skirtingom dienom (pvz. kažkaip pažymi kad važinės tuo mašrutu 8h ryto 1d-5d ateinančias keturias savaites). Tada mes sukuriam jam daug tripų (pavyzdiniu atveju 20) Ir toliau visa tai funkcionuoja kaip atskiros kelionės. Tai manau gana stipriai supaprastintų tolimesnę implementaciją.

**Comment by VaivaK** [comment]
Mano nuomone kelionė sistemoje vistiek turi būti traktuojama kaip individuali kelionė, nes ir vertinimai pagal tai eis kada nors. Todėl net jei ji kartojasi kiekvieną dieną, vistiek "pirmadienio" kelionė yra viena kelionė, o antradienio kita. Man repeating sprendimas nepatinka, nes mes jo nesam gražiai vizualiai išsprendę ir gali būti daug komplikaicjų. Pvz kad rideris tikria pasirinktų dieną, kai jam reikia važiuoti. Pvz kad driveris patogiai galėtų nucancelinti vieną dieną iš savo savaitės uždėtų kelionių, o ne kancelintų visas keliones ir tokių "klausimų" yra daugiau. Ir mes dabar manau truputi neturim kada į juos gilintis, nes yra tikrai svarbesnių sprendimų. Mano nuomone paprastesnis variantas (meet in the middle kad ir driveriui būtų truputi patogiau ir mums lengviau) tai suteikti galimybę atsidarius istoriją "dublikuoti" kelionę ir tik pataisyti datą/ laiką.
Beje, tokia funkcija reikalinga ir driveriui ir raideriui.

**Comment by ArnoldasSid** [comment]
Čia gal ne visiškai į temą, bet man klausimas toks jau seniai kirba: Ar mum tikrai MVP būtinos Riderio kelionės? Čia man atrodo labiau nice to have, negu kažkas tikrai dabar reikalingo. Tai gal būtų prasmės bent jau laikinai išmesti?

**Comment by VaivaK** [comment]
Pakomentuok plačiau

**Comment by ArnoldasSid** [comment]
Na čia asmeninė nuomonė, bet intuityviai man atrodo, kad atėjęs į appsą susirandi kelionę kuri tau tinka, paspaudi request ir viskas. O kurti kažkokį "Your Ride" žmonėm greičiausiai bus neaišku kas tai yra išvis ir kam to reikia.

Bendrai paėmus aš nelabai įsivaizduoju scenarijaus, kai norėtum susikurti Ride ir gauti notificationus. Manau vistiek kai planuoji kelionę kažkur pažiūri ar yra kas paveš, o jei nėra tai planuoji kitas alternatyvas kaip nusigauti. Realiai matau tik vieną praktišką scenarijų šitos funkcijos:
- Kai jei kasnors paveš tai važiuosi jei ne tai niekur nevažiuosi (nelabai manau tokių variantų būna kelionėms mieste)

Šiaip bendrai paėmus manau mūsų appsas manau suteikia alternatyvą kitoms susisiekimo priemonėms o ne jas pakeičia. Todėl iš riderio pusės toks funkcionalumas kaip "pažiūri ar kelionė yra ir jei yra kažkas patogiau negu šiaip būtum keliavęs tai pasinaudoji carpoolu, o jei ne tai keliauji kaip šiaip būtum keliavęs" yra pakankamas.

**Comment by spastai** [comment]
Disable for now as it makes complications
