### ISSUE TITLE
Question: Leaflet.js & OpenStreetMaps vs. Google maps pros/cons?

### ISSUE THREAD

**Issue by dalerka** [vilnius/vilnius-carpool#206]
Hey guys, this is a very interesting project and thank you for making it open source!
I'm curious if there are any downsides in using Leaflet.js + OpenStreetMaps instead of Google maps for such project?

**Comment by spastai** [comment]
Thanks. 
Regarding switching to more open map alternatives - there are no objectives not to do so, just google products were chosen as we are aiming for minimal viable product, to speedup development. 
However it should be possible to switch to other map providers - just they have to assure maps and routing functions.
