### ISSUE TITLE
Suggestion: NativeBase (ReactNative) for mobile?

### ISSUE THREAD

**Issue by dalerka** [vilnius/vilnius-carpool#207]
Hi guys, 
FYI, [NativeBase](https://github.com/GeekyAnts/NativeBase) can help with cross-mobile (Android, iOS) components (based on React Native) and thus improve UX and maintenance. 
What are the downsides of using NativeBase for such project?

**Comment by spastai** [comment]
The downsides are that most of the UI code should be rewritten (despite of the fact that current code is on  react). 
Things like material-ui currently used, would be complicated to implement on ReactNative also.

**Comment by dalerka** [comment]
I see, thanks for clarification!
