### ISSUE TITLE
API for apps

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#29]

**Comment by spastai** [comment]
Please close the issue if you can proceed with you task or put comments/requirements if something is missing.
For websocket on iOS I would recomment to look into 
https://github.com/boundsj/ObjectiveDDP
or 
https://github.com/martijnwalraven/meteor-ios/graphs/contributors

Using DDP from the start might simplify following tasks:
- User authentication
- Server data updates (data sending from server)

**Comment by spastai** [comment]
Try 
`curl -XGET http://arciau.lt/api/user/CHh5JGfoqWHSidpAd/location`
it should return 
`{"loc":[25.26246500000002,54.6779097],"tsi":"2016-03-17T04:35:58.126Z","userId":"CHh5JGfoqWHSidpAd","_id":"jEW3cd4DqpASGfPT5"}`

To post:
`curl -XPOST http://arciau.lt/api/user/CHh5JGfoqWHSidpAd/location -H "Content-Type: application/json" -d '{"loc":[25.26246500000002,  54.6779097]}'`

**Comment by dariukas** [comment]
Session Error is Optional(Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x7f98214ca470 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=51, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://arciau.lt/api/user/CHh5JGfoqWHSidpAd/location, NSErrorFailingURLKey=http://arciau.lt/api/user/CHh5JGfoqWHSidpAd/location, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=51, NSLocalizedDescription=Could not connect to the server.})

**Comment by dariukas** [comment]
I also tried Meteor framework (https://github.com/martijnwalraven/meteor-ios), for iOS9&XCode7 there is an update: https://github.com/edwardvalentini/meteor-ios/tree/xcode7

However, lately I got an issue:

ld: '/Users/dariukas/Downloads/meteor-ios-xcode7/Carthage/Build/iOS/InflectorKit.framework/InflectorKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

**Comment by dariukas** [comment]
Thanks, I wrote comments about the issues.

**Comment by dariukas** [comment]
<img width="1280" alt="screen shot 2016-03-23 at 00 39 01" src="https://cloud.githubusercontent.com/assets/4546421/13970171/d175330a-f08f-11e5-8bfa-4e3e82bb8ec2.png">

I made some changes to avoid linker error. I changed the settings from "Yes" to "No".

**Comment by dariukas** [comment]
Both works, they return dictionaries.

POST:
 {
    status = ok;
}

GET:
 {
    "_id" = GinQTxBWmNGk4Ezjr;
    loc =     (
        "25.26246500000002",
        "54.6779097"
    );
    tsi = "2016-03-23T07:31:27.245Z";
    userId = CHh5JGfoqWHSidpAd;
}

**Comment by spastai** [comment]
arciau.meteor.com will be kept as staging
arciau.lt meanwhile is down, but after restoration should become production environment
