### ISSUE TITLE
Migrate tripForm to react

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#33]
Trip form could be found http://localhost:3000/trip/ 
Currently it's quite hard to use material-ui so I would suggest to use more lightweight components.
Regarding design bootstrap/3.1.1 is used 
Please:
- [x] Apply bootstrap looking how it is done in [blaze way](https://github.com/vilnius/vilnius-carpool/blob/master/src/packages/carpool-view-map/components/trip-form/CarpoolTrip.html#L2-L50) 
- [x] Remove blaze form
- [x] Add internalization. Currently blaze helper "t" is written and [used](https://github.com/vilnius/vilnius-carpool/blob/master/src/packages/carpool-view-map/CarpoolMap.html#L13), which loads messages from [json structure](https://github.com/vilnius/vilnius-carpool/blob/master/src/packages/carpool-view-map/CarpoolMap_i18n.coffee). Cheap and dirty. Please suggest better ways.
- [x] Implement trip saving logic - see [save event](https://github.com/vilnius/vilnius-carpool/blob/master/src/packages/carpool-view-map/CarpoolMap.coffee#L13-L25)
- [ ] Currently there is a logic which changes icon when geolocation of the address is [detected](https://github.com/vilnius/vilnius-carpool/blob/master/src/packages/carpool-view-map/CarpoolMap.html#L14-L18). currentTrip.to.getLatlng is reactive - when the value is [set](https://github.com/vilnius/vilnius-carpool/blob/master/src/packages/carpool-view-map/MapView.coffee#L135) the template is rerendered - how this could be implemented in react?

Optionally
- [ ] Implement / adopt cucumber test for this page. See [post-trip](https://github.com/vilnius/vilnius-carpool/blob/master/src/tests/cucumber/features/uc8-post-trip.feature#L11) - almost the same test could be reused just changing [step](https://github.com/vilnius/vilnius-carpool/blob/master/src/tests/cucumber/features/uc8-post-trip.feature#L13) to 
  `And I see "#trip-toAddress" in "/trip"`

**Comment by spastai** [comment]
@ArnoldasSid  New branch for MUI was created https://github.com/spastai/vilnius-carpool/tree/0.1.9/refactor/meteor-1.3 - and pull request for this #47 

Try to move the code from https://github.com/spastai/meteor-carpool-react-material-test/blob/master/client/components/TripForm.jsx
Also check http://guide.meteor.com/ui-ux.html#i18n

If something is missing - write here

**Comment by spastai** [comment]
Please describe what tap/i18n issues you faced

**Comment by ArnoldasSid** [comment]
I think it just doesn't find my translations in i18n folder. Because TAPi18n.__('labelFrom') just returns 'labelFrom' and it doesn't register that I have multiple languages defined

I have described labels here
https://github.com/vilnius/vilnius-carpool/blob/0.1.9/refactor/meteor-1.3/src/packages/carpool-view-mui/i18n/en.i18n.json

And I am using them here 
https://github.com/vilnius/vilnius-carpool/blob/0.1.9/refactor/meteor-1.3/src/packages/carpool-view-mui/components/trip-form/TripForm.jsx

**Comment by spastai** [comment]
Fix for a tap is on my branch: https://github.com/spastai/vilnius-carpool/commit/35ecd2403c5613765b4a26c7ee0631b2889092b2

**Comment by spastai** [comment]
I'm not sure will we do anything more for this task?
Are we planning to implement indication on successful geo location, which shows that address entered by user could be located on map - https://www.thinkwithgoogle.com/articles/chapter-5-form-entry.html says that error should be shown - would it be possible to show yellow field box while address is not detected?
