### ISSUE TITLE
Change of the front-end look and feel framework

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#36]
There are variety of the libraries that help to create look and feel of the application. This discussion is  about selected options and possible alternatives
Currently [bootstrap](http://getbootstrap.com/) is used - the rationale for this was to use responsive design and save time on doing things from the scratch. As we are targeting mobile users (the problem we are solving is being best solved with mobile devices) [mobile-first](https://www.smashingmagazine.com/2012/06/sketching-a-new-mobile-web/) approach is very important.
However there should be always the dialog on the better ways to do things. One of the alternatives is i.e. [Material-UI](http://www.material-ui.com/#/). Unfortunately it's quite hard to use it with current version of meteor.
Keep in mind that [react native](https://facebook.github.io/react-native/) is something to consider
Please suggest your options, arguments to use other alternatives

**Comment by ArnoldasSid** [comment]
Few quick thoughts:
- Meteor+Blaze+Bootstrap probably will get us to working app in the shortest amount of time.
- Using React Native and/or making native apps might be better in long run.
- As far as android is concerned (which is majority of our app users) I believe material design is vastly superior to what bootstrap has to offer. But might be harder to make (quality vs. speed once again).
- We should decide what our MVP is, when we want to have it and make decisions accordingly.

**Comment by spastai** [comment]
I agree with @ArnoldasSid comments. Just keep in mind that react was introduce to widen developers range - those who are familiar with react can also contribute to this project.
Current MVP is defined only as a [workflow](https://github.com/vilnius/vilnius-carpool/wiki/Functional-view) but wireframe is on the way.
So keep writing on react or blaze, whatever you prefer. Also keep in mind their [performance](http://info.meteor.com/blog/comparing-performance-of-blaze-react-angular-meteor-and-angular-2-with-meteor)
