### ISSUE TITLE
Implement authentication for REST API

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#37]

**Comment by spastai** [comment]
I have updated https://github.com/vilnius/vilnius-carpool/wiki/Rest-API
and deployed code to staging arciau.meteor.com

Please close the issue if everything works

**Comment by dariukas** [comment]
@spastai , can I send any user name as far as it is trying to register and get token? Don't you think it is better to assign ids for users for their usernames (just asking)?

**Comment by spastai** [comment]
Well first you should register user.
Now arciau.meteor.com is down but arciau.lt is up again so go to http://arciau.lt/register or use user1@tiktai.lt / aaa on arciau.lt
