### ISSUE TITLE
Notification test

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#41]
1. Everyone should register on [arciau.lt](arciau.lt) 
2. Preferably install android [application](https://github.com/spastai/vilnius-carpool/raw/master/dist/Carpool-0.0.3.apk)
3. The  enter trip as rider to: "Konstitucijos pr. 3, Vilnius", from: "31 Medeinos g. Vilnius"
4. I will add the same trip as driver 
5. You should get notifications

Write all comments here - this might be an input for later discussions

**Comment by dariukas** [comment]
@spastai , @VaivaK , the notification via Apple can be send only in the case of the certificates from the account of apple we have.

**Comment by VaivaK** [comment]
@dariukas  - ar mes kalbam apie apple developer accounta? jau mums jo reikia ar dar turim laiko?

**Comment by VaivaK** [comment]
@spastai padariau kaip sakei, tik per weba. Pastebėjimai:
1. neįvedžiau laiko, tai liko tarsi "šią minutę" ir man rado 3 tripus. Bet nerodo kokiais laikais jie vyksta.
2. šiaip nerodo jokios info apie driverį, nei vardo nei foto nei nieko. tas atrodo kažkaip nepatikimai.
3. kas yra šalia matomas "link"?
4. "reguest" išsiunčiau, bet negaunu jokio feed-backo, kad requestas išsiųstas. Reikia reakcijos į atliktą veiksmą.
5. Norint paspausti "request" man pirma reikia paspausti ant rodyklės žemyn, kad išsiskleistų platesnis meniu. tai nėra patogus UX, ne savaime suprantama. idealiu atveju žmogui nieko plačiau nereikėtų išskleidinėti.
6. "patampius" ekraną (sumažinus, padidinus) šone esanti išnaša "notifications" liko ne vietoj. pridedu screanshoot'ą 
7. Kas yra tas blokas tarp reikalingos suvesti medžiagos ir jau rastu kelionių? ten yra mano suvesta informacija ir tada "link" bei "X". kam jo reikia?
8. Suvedus informaciją ir paprašius rasti kelionių, pirmam informacijos bloke (kur vedam iš kur į kur it tt) iš kur infomacija lieka, o į kur nelieka. Kodėl? Kokia čia logika?
9. kaip suprantu kol kas stotelių visai nematom ir nelinkinam?
![screen shot 2016-03-29 at 14 20 17](https://cloud.githubusercontent.com/assets/17546849/14106443/d1dbcfaa-f5b9-11e5-9f81-57995ed6ac66.png)
