### ISSUE TITLE
Implement user registration on REST API

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#46]
@dariukas I have a doubt can the same method, which returns token  http://arciau.meteor.com/api/access_token be used for user registration - what if user has account and mistypes username? new user will be created?

**Comment by spastai** [comment]
https://github.com/vilnius/vilnius-carpool/wiki/Rest-API#accounts

**Comment by dariukas** [comment]
@spastai, yes, you are right. Moreover, registration service needs the name, some other info, so, let's have a separate service for registration.
