### ISSUE TITLE
Describe and implement RideOffer page for android hybrid

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#65]
From [wireframe](https://github.com/vilnius/vilnius-carpool/wiki/Functional-view#wireframe)
![https://cloud.githubusercontent.com/assets/15831041/14581041/3c09e7b6-03ea-11e6-99ae-784d43452c79.png](https://cloud.githubusercontent.com/assets/15831041/14581041/3c09e7b6-03ea-11e6-99ae-784d43452c79.png)
- [x] mark starting point 
- [x] finish point 
- [x] draw trip

**Comment by spastai** [comment]
Need consultancy - should we use existing libraries for react-gmaps integration like:
https://github.com/tomchentw/react-google-maps (last commits on Feb 22, 2016; 167 forks)
https://github.com/istarkov/google-map-react (last commit on Apr 7, 2016; 73 forks)
or write component by ourselves ?

**Comment by ArnoldasSid** [comment]
I believe at least for the start we should really try to use what is available for faster progress, and later we can reevaluate. We just need to check if libraries support the main features we need for our app.

**Comment by ArnoldasSid** [comment]
So the question is what do we need? I assume we need to mark starting point finish point and the route driver will take, anything else?

**Comment by spastai** [comment]
By the way is 
http://stg.arciau.lt/mui/screen3 = RequestRide (this task is about this view). 
It would be good to use the same terms as in 
https://github.com/vilnius/vilnius-carpool/wiki/Functional-view#wireframe

**Comment by ArnoldasSid** [comment]
Yes, noted, will change.

**Comment by spastai** [comment]
I think selecting dependencies should be done more carefully (lesson learned from tap:i18n).

First it should be possible to use library easy in the beginning - if still doesn't work well in couple of hours, it should be parked. 

Next, we should always evaluate gain/pain ratio: i.e. gmaps api is well developed by google and what we need here is integration layer in react. Will will bring some solutions (like library loading,  correct lifecycle inside react and etc), but it will have some limitations (even gmaps library loading might not corespond our needs, maybe we will not be able to use gmaps in a way we want and etc). 

Then the issues that is hard foresee: like which routing library to use: iron-rout or flow-router? Only having done almost all project you see pros and cons.

Thus I will do "easy to use" test with https://github.com/tomchentw/react-google-maps and then we can discuss about gain/pain
