### ISSUE TITLE
Data loading in react

### ISSUE THREAD

**Issue by ArnoldasSid** [vilnius/vilnius-carpool#70]
Might be worth discussing how we load data.

https://www.discovermeteor.com/blog/data-loading-react/

I like the option 3 here, any thoughts on that?

**Comment by spastai** [comment]
Well the article is dated Mar 2 2016 and in the end of march we've got meteor 1.3 which suggest to solve the problem such way: http://guide.meteor.com/react.html#data

This was used in https://github.com/vilnius/vilnius-carpool/blob/master/src/packages/carpool-view-mui/components/landing/Landing.jsx#L68

Moreover similar approach was used in last my last PR #68 (see description)
