### ISSUE TITLE
Bad width detection on mobile device

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#88]
Layout fails on mobile devices:
![Mobile view](https://cloud.githubusercontent.com/assets/1442758/15290149/43f7c18a-1b7f-11e6-9713-b66bd590157f.png)

**Comment by spastai** [comment]
Still same view on Note 4 even using crosswalk plugin for Cordova Android app (#106 didn't helped also)

**Comment by ArnoldasSid** [comment]
Is it fixed?

**Comment by spastai** [comment]
The problem seems to be related with #139. 
Now on Note4 and s3 even cordoba app looks ok.
