### ISSUE TITLE
Find place for profile information

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#91]
Currently it's in menu, but with long names doesn't look nice:
![screenshot from 2016-05-17 05 54 25](https://cloud.githubusercontent.com/assets/1442758/15309921/e941eb38-1bf3-11e6-8720-81a0900d35a3.png)

**Comment by RenatBuga** [comment]
Wy not placing Logout in My Profile page as per wireframe? I bet users
won't use it frequently and the problem with long names will be solved.

On Tuesday, May 17, 2016, spastai notifications@github.com wrote:

> Currently it's in menu, but with long names doesn't look nice:
> [image: screenshot from 2016-05-17 05 54 25]
> https://cloud.githubusercontent.com/assets/1442758/15309921/e941eb38-1bf3-11e6-8720-81a0900d35a3.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/vilnius/vilnius-carpool/issues/91

## 

## 

Renat BUGA
